version: '3.8'

services:
  web:
    build: .
    container_name: gloria_komputer_inventory
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=/data/inventory.db
      - SECRET_KEY=change-this-in-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "docker-healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./data:/data
